# Generated by Django 5.0.11 on 2025-02-13 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField()),
                ('expense_name', models.TextField(max_length=25)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.BooleanField()),
                ('installments', models.PositiveSmallIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField()),
                ('finance_name', models.TextField(max_length=25)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_payed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=4, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('income_name', models.TextField(max_length=25)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regular_income', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField()),
                ('loan_name', models.TextField(max_length=25)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_payed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=4, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
